movie_database/movie_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='home_page'),
    path('media_list/', views.MediaListView.as_view(), name='all_media'),
    path('media_list/<int:pk>/', views.MediaDetailView.as_view(), name='media'),
    path('companies/<int:company_id>/', views.company, name='company'),
    path('people/<int:person_id>/', views.person, name='person'),
    path('watchlist/', views.WatchlistView.as_view(), name='watchlist'),
    path('add_entry/<int:pk>/', views.WatchlistCreate.as_view(), name='user_watchlist_create'),
    path('delete_entry/<int:pk>/', views.WatchlistDeleteView.as_view(), 
    name='user_watchlist_delete'),
]

movie_database/movie_database/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('movie_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('user_profile/', include('user_profile.urls')),
] + static(settings.STATIC_URL, document_root= settings.STATIC_ROOT)\
    +static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

movie_database/movie_app/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.urls import reverse
from django.utils.html import format_html
from django.contrib.auth import get_user_model


class Role(models.Model):
    name = models.CharField(_('name'), max_length=150)

    def __str__(self) -> str:
        return f"{self.name}"

    class Meta:
        verbose_name = _('role')
        verbose_name_plural = _('roles')


class Person(models.Model):
    first_name = models.CharField(_('first name'), max_length=150)
    last_name = models.CharField(_('last name'), max_length=150)
    country = models.CharField(_('country'), max_length=150)
    photo = models.ImageField(_('photo'), upload_to='cast_photos', blank=True, null=True)

    def __str__(self)->str:
        return f"{self.first_name} {self.last_name}"
    
    class Meta:
        verbose_name = _('person')
        verbose_name_plural = _('people')


class Location(models.Model):
    name = models.CharField(_('location name'), max_length=255,)
    country = models.CharField(_('country'), max_length=150)

    def __str__(self) -> str:
        return f"{self.name}, {self.country}"

    class Meta:
        ordering = ['country']
        verbose_name = _('location')
        verbose_name_plural = _('locations')


class Genre(models.Model):
    name = models.CharField(_('genre name'), max_length=150)

    def link_filtered_medias(self):
        link = reverse('all_media')+'?genre_id='+str(self.id)
        return format_html('<a class="genre" href="{link}">{name}</a>', link=link, name=self.name)

    def __str__(self) -> str:
        return f"{self.name}"

    class Meta:
        verbose_name = _('genre')
        verbose_name_plural = _('genres')


class Company(models.Model):
    name = models.CharField(_('company name'), max_length=150)
    country = models.CharField(_('country'), max_length=150)

    def __str__(self) -> str:
        return f"{self.name} ({self.country})"

    class Meta:
        ordering = ['country']
        verbose_name = _('company')
        verbose_name_plural = _('companies')


class Language(models.Model):
    name = models.CharField(_('language'), max_length=150)

    def __str__(self) -> str:
        return f"{self.name}"

    class Meta:
        verbose_name = _('language')
        verbose_name_plural = _('languages')

class Media(models.Model):
    name = models.CharField(_('movie/series name'), max_length=150)
    release_date = models.DateField(_('release date'), null=True, blank=True)
    score = models.FloatField(_('score'), null=True, blank=True)
    duration = models.IntegerField(_('duration'), null=True, blank=True)
    is_series = models.BooleanField(_('is series?'), default=False)
    poster = models.ImageField(_('poster'), upload_to='posters', blank=True, null=True)
    trailer = models.CharField(_('trailer link'), max_length=255, blank=True, null=True)
    pg_rating = models.CharField(_('PG rating'), max_length=150, blank=True, null=True)
    summary = models.TextField(_('summary'), blank=True, null=True)
    tagline = models.CharField(_('tagline'), max_length=255, blank=True, null=True )
    budget = models.IntegerField(_('budget'), blank=True, null=True)
    box_office = models.IntegerField(_('box office'), blank=True, null=True)

    location = models.ManyToManyField(Location, verbose_name=_('location'), related_name='medias', blank=True)
    genre = models.ManyToManyField(Genre, verbose_name=_('genre'), related_name='medias', blank=True)
    company = models.ManyToManyField(Company, verbose_name=_('company'), related_name='medias', blank=True)
    language = models.ManyToManyField(Language, verbose_name=_('language'), related_name='medias', blank=True)

    @property
    def series_length(self):
            length = 0
            for season in self.seasons.all():
                length += season.season_length
            return length

    def save(self, *args, **kwargs):
        if self.is_series:
            self.duration = self.series_length
        super(Media, self).save(*args, **kwargs)

    @property
    def convert_time(self):
        readable_time = ""
        hours = self.duration // 60 
        minutes = self.duration % 60 
        if hours != 0:
            readable_time += f"{hours}h  "
        if minutes != 0:
            readable_time += f"{minutes}min"
        return readable_time

    def __str__(self) -> str:
        return f"{self.name} ({self.release_date.strftime('%Y')})"

    class Meta:
        verbose_name = _('media')

class Watchlist(models.Model):
    list_owner = models.ForeignKey(get_user_model(),
        verbose_name = _('list owner'),
        on_delete = models.SET_NULL,
        blank = True,
        null = True,
        related_name = "watchlist",)
    media = models.ForeignKey(Media, verbose_name=_('media'), on_delete=models.CASCADE, related_name='watchlist', blank=True)
    date_added = models.DateField(_('date added'), auto_now_add=True, null=True)

    def __str__(self) -> str:
        return f"{self.media.name}, {self.list_owner}"

    class Meta:
        verbose_name = _('watchlist')
        verbose_name_plural = _('watchlists')


class CastCrew(models.Model):
    role = models.ForeignKey(Role, 
        on_delete=models.CASCADE, 
        verbose_name=_("role"), 
        related_name='cast_crew'
        )
    person = models.ForeignKey(Person, 
        on_delete=models.CASCADE, 
        verbose_name=_("person"), 
        related_name='cast_crew'
        )
    media = models.ForeignKey(Media, 
        verbose_name=_("media"), 
        on_delete=models.CASCADE, 
        related_name='cast_crew'
        )

    def __str__(self) -> str:
        return f"{self.person} - {self.role} ({self.media})"

    class Meta:
        verbose_name = _('cast_crew')

class Season(models.Model):
    media = models.ForeignKey(Media, 
        limit_choices_to={'is_series' : True},
        null = True,
        verbose_name=_("media"), 
        on_delete=models.CASCADE, 
        related_name="seasons"
        )
    number = models.IntegerField(_("season number"), null=True, blank=True)
    
    @property
    def season_length(self):
        length = 0
        for episode in self.episodes.all():
            length += episode.duration
        return length
            
    def __str__(self) ->str:
        return f"{self.number} - {self.media}"

    class Meta:
        verbose_name = _('season')
        verbose_name_plural = _('seasons')


class Episode(models.Model):
    duration = models.IntegerField(_('duration'), default=0)
    release_date = models.DateField(_('release date'), null=True, blank=True)
    season = models.ForeignKey(Season, verbose_name=_('season'), on_delete=models.CASCADE, related_name="episodes")
    number = models.IntegerField(_("episode number"), null=True, blank=True)
    name = models.CharField(_('episode name'), max_length=150, null=True, blank=True)

    def __str__(self) ->str:
        return f"{self.number} {self.season}"

    class Meta:
        verbose_name = _('episode')
        verbose_name_plural = _('episodes')


class MediaComment(models.Model):
    media = models.ForeignKey(Media, verbose_name=_("media"), on_delete=models.CASCADE, related_name='comments')
    comment_author = models.ForeignKey(get_user_model(), verbose_name=_("comment author"), on_delete=models.CASCADE, related_name='comments')
    created_at = models.DateTimeField(_("created at"), auto_now_add=True)
    comment = models.TextField(_("comment"), max_length=10000)

    def __str__(self):
        return f"{self.comment_author} on {self.media} at {self.created_at}"

    class Meta:
        ordering = ['-created_at',]

movie_database/movie_app/forms.py
from django import forms
from . models import Watchlist, MediaComment
from django.utils.timezone import datetime, timedelta


class WatchlistForm(forms.ModelForm):
    class Meta:
        model = Watchlist
        fields = ('list_owner', 'media')
        widgets = {
            'list_owner': forms.HiddenInput(),
            'media': forms.HiddenInput(),
        }

class MediaCommentForm(forms.ModelForm):
    def is_valid(self) -> bool:
        valid = super().is_valid()
        return valid
    
    class Meta:
        model = MediaComment
        fields = ('comment', 'media', 'comment_author', )
        widgets = {
            'media' : forms.HiddenInput(),
            'comment_author' : forms.HiddenInput(),
        }

movie_database/movie_app/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.generic import ListView, DetailView, DeleteView, CreateView
from django.urls import reverse, reverse_lazy
from django.contrib import messages
from . models import Media, Person, Company, Genre, Watchlist
from django.views.generic.edit import FormMixin
from django.db.models import Q
from . forms import WatchlistForm, MediaCommentForm
from django.utils.translation import gettext_lazy as _

def index(request):
    return render(request,'movie_app/home_page.html')

def media(request, media_id):
    return render(request, 'movie_app/media.html', {'media': get_object_or_404(Media, id=media_id)})

def company(request, company_id):
    return render(request, 'movie_app/company.html', {'company': get_object_or_404(Company, id=company_id)})

def person(request, person_id):
    return render(request, 'movie_app/person.html', {'person': get_object_or_404(Person, id=person_id)})

class MediaListView(ListView):
    model = Media
    paginate_by = 10
    template_name = 'movie_app/media_list.html'

    def get_queryset(self):
        queryset = super().get_queryset()
        search = self.request.GET.get('search')
        if search:
            queryset = queryset.filter(Q(name__icontains=search)) 
        if self.request.GET.get("is_series") != None:
            queryset = queryset.filter(is_series=self.request.GET.get("is_series"))
        genre_id = self.request.GET.get('genre_id')
        if genre_id:
            queryset = queryset.filter(genre__id=genre_id)
        return queryset.order_by('release_date')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        genre_id = self.request.GET.get('genre_id')
        context['genres'] = Genre.objects.all()
        if genre_id:
            context['genre'] = get_object_or_404(Genre, id=genre_id)
        return  context


class MediaDetailView(FormMixin, DetailView):
    model = Media
    template_name = 'movie_app/media.html'
    form_class = MediaCommentForm

    def get_success_url(self):
        return reverse('media', kwargs={'pk' : self.get_object().id})

    def post(self, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            messages.error(self.request, _("Please don't spam!"))
            return self.form_valid(form)
        
    def get_initial(self):
        return {
            'media' : self.get_object(),
            'comment_author' : self.request.user,
        }
    
    def form_valid(self, form):
        form.instance.media = self.get_object()
        form.instance.comment_author = self.request.user
        form.save()
        messages.success(self.request, _('Your comment has been posted!'))
        return super().form_valid(form)
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if Watchlist.objects.filter(list_owner=self.request.user, media=self.object).exists():
            context['in_watchlist'] = True
        else:
            context['in_watchlist'] = False
        return context
    

class WatchlistView(LoginRequiredMixin, ListView):
    model = Watchlist
    paginate_by = 10
    template_name = 'movie_app/user_watchlist.html'

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(list_owner=self.request.user).order_by('date_added')
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        queried_watchlist = self.object_list
        watchlist_duration = 0
        for entry in queried_watchlist:
            watchlist_duration += entry.media.duration
        readable_time = ""
        days = watchlist_duration // 1440
        hours = (watchlist_duration % 1440) // 60 
        minutes = (watchlist_duration % 1440) % 60 
        if days != 0:
            readable_time += f"{days} days "
        if hours != 0:
            readable_time += f"{hours} hours "
        if minutes != 0:
            readable_time += f"{minutes} minutes"
        context['converted_time'] = readable_time
        context['watchlist_count'] = queried_watchlist.count()
        return context

    

class WatchlistCreate(LoginRequiredMixin, CreateView):
    model = Watchlist
    form_class = WatchlistForm
    template_name = 'movie_app/user_watchlist_add.html'

    def form_valid(self, form):
        form.instance.list_owner = self.request.user
        form.instance.media = Media.objects.get(pk=self.kwargs['pk'])
        messages.success(self.request, f'{form.instance.media.name} was added to your watchlist!')
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('media', kwargs={'pk': self.kwargs['pk'] })


class WatchlistDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Watchlist
    template_name = 'movie_app/user_watchlist_delete.html'
    success_url = reverse_lazy('watchlist')

    def test_func(self):
        watchlist_entry = self.get_object()
        return self.request.user == watchlist_entry.list_owner

    def form_valid(self, form):
        watchlist_entry = self.get_object()
        messages.success(self.request, f'{watchlist_entry.media.name} was removed from your watchlist.')
        return super().form_valid(form)

movie_database/movie_app/templates/movie_app/base.html
<!DOCTYPE html>
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} Movie db {{ block.super }} {% endblock title %}</title>
    <link rel="stylesheet" href="{% static 'movie_app/css/base.css' %}">
    <link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Ubuntu" />
</head>
<body>
    <header>
        <div class="container">
            {% block nav %}
            <a href="{% url 'home_page' %}">HOME</a>
            <a href="{% url 'all_media' %}?is_series=0">MOVIES</a>
            <a href="{% url 'all_media' %}?is_series=1">SERIES</a>
            <a href="{% url 'all_media' %}">GENRES</a>
            <div class="right-side">
            {% if user.is_authenticated %}
                <a class="user-name" href="{% url 'profile' %}">Hi, {{ user }}!</a>
                <a href="{% url 'watchlist' %}">My Watchlist</a>
                {% if user.is_superuser or user.is_staff %}
                    <a href="{% url 'admin:index' %}"> Admin</a>
                {% endif %}
                <a href="{% url 'logout' %}">Logout</a>
            {% else %}
                <a href = "{% url 'register' %}">Register</a>
                <a href="{% url 'login' %}{% if not '/accounts/' in request.path %}?next={{ request.path }}{% endif %}">Login</a>
            {% endif %}
            </div>
            {% endblock nav %}
        </div>
    </header>
    <main>
        <div class="container">
            {% if messages %}
                {% for message in messages %}
                    <div class="alert alert-{{ message.tags }}">{{ message }}</div>
                {% endfor %}
            {% endif %}
                {% block content %} 
                {% endblock content %}
        </div>
    </main>
    <footer>
        <div class="container">
            {% block footer %} <p> footer goes here</p>{% endblock footer %}
        </div>
        
    </footer>
</body>
</html>

movie_database/movie_app/templates/movie_app/company.html
{% extends 'movie_app/base.html' %}
{% load static %}
{% block title %} {{company.name}} {{ block.super }} {% endblock title %}
{% block content %}
    <h1>{{ company.name }} </h1>
    <h2>{{ company.country }} </h2>
    <h2> Production </h2>
        <ul>
            {% for media in company.medias.all %}
            <li> <a class="cast" href="{% url 'media' media.pk %}">{{ media }} </a> </li>
            {% endfor %}
        </ul>

{% endblock content %}

movie_database/movie_app/templates/movie_app/home_page.html
{% extends 'movie_app/base.html' %}
{% block title %}WELCOME TO MOVIE DATABASE{{ block.super }} {% endblock title %}
{% block content %}
<h1>MOVIE DATABASE</h1>                            
{% endblock content %}

movie_database/movie_app/templates/movie_app/media.html
{% extends 'movie_app/base.html' %}
{% load static %}
{% block title %} {{object}} {{ block.super }} {% endblock title %}
{% block content %}
    <div class="media-details-container">
        <div class="media-details">
            {% if object.poster %}
              <img src="{{object.poster.url}}">
            {% else %}
              <img src="{%  static 'movie_app/img/no_poster.jpg' %}">
            {% endif %}
        </div>
        <div class="media-details media-backg">
            {% if in_watchlist %}
                <p><a class="add-to-watchlist" href="{% url 'watchlist' %}">In your watchlist</a></p>
            {% else %}
                <p><a class="add-to-watchlist" href="{% url 'user_watchlist_create' object.pk %}">Add to your watchlist</a></p>
            {% endif %}
            <h1>{{ object.name }} </h1>
            {% if object.release_date %}<h2>Release date {{ object.release_date }}</h2>{% endif %}
            {% if object.score %}<h2>Score {{ object.score }}</h2>{% endif %}
            {% if object.convert_time %}<h2>Duration {{ object.convert_time }} </h2>{% endif %}
            {% if object.pg_rating%}<h2>Rated {{ object.pg_rating }}</h2>{% endif %}
            {% if object.tagline %}<h2>Tagline: {{ object.tagline }}</h2>{% endif %}
            {% if object.budget %}<h2>Budget - {{ object.budget}}$</h2>{% endif %}
            {% if object.box_office %}<h2>Box office - {{ object.box_office }}$</h2>{% endif %}
            {% if object.summary %}<h2>Summary: {{ object.summary }}</h2>{% endif %}
            {% if object.cast_crew.count %}
            <h3> Cast and Crew </h3>
            <ul>
            {% for castcrew  in object.cast_crew.all %}
                <li>  {{castcrew.role}} <a class="cast" href="{% url 'person' castcrew.person.pk %}" > {{ castcrew.person }}</a> </li>
            {% endfor %}
            </ul>
            {% endif %}
            {% if object.company.count %}
            <h3> Produced by</h3>
                <ul>
                {% for company  in object.company.all %}
                    <li>  <a class="cast" href="{% url 'company' company.pk %}"> {{ company }}</a> </li>
                {% endfor %}
                </ul>
            {% endif %}
            {% if object.location.count %}
            <h3>Filming locations</h3>
                <ul>
                {% for location  in object.location.all %}
                    <li> {{ location }}</li>
                {% endfor %}
                </ul>
            {% endif %}
            {% if object.language.count %}
            <h3>Languages</h3>
                <ul>
                {% for language  in object.language.all %}
                    <li> {{ language }}</li>
                {% endfor %}
                </ul>
                {% endif %}

            </div>
    </div>
    <div class="series">
        {% if object.is_series == True %}
            <ul>
                {% for season in object.seasons.all %}
                <li>
                    <h3> Season {{ season.number }}</h3>
                        <ul>
                            {% for episode in season.episodes.all %}
                                <li>S{{ season.number }}E{{ episode.number }} - {{ episode.name }}<li>
                            {% endfor %}
                        </ul>
                </li>
                {% endfor %}
            </ul>
        {% endif %}
    </div>
    {% if user.is_authenticated %}
    <div class="comment-form">
        <h3>You can leave a comment here:</h3>
        <form action="" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button class="button" type="submit"> Add a comment </button>
        </form>    
    </div>
    {% endif %}
    {% if object.comments.count %}
    <h2> COMMENTS </h2>
        {% for comment in object.comments.all%}
            <div class="media-comment">
                <h4> {% if comment.comment_author.profile.photo %}
                    <img src="{{ comment.comment_author.profile.photo.url}}">
                    {% endif %}
                {{ comment.comment_author }} 
                    <span class="float-right"> {{ comment.created_at }}</span></h4>
                <p>{{ comment.comment }} </p>
            </div>
        {% endfor %}
    {% endif %}
{% endblock content %}

movie_database/movie_app/templates/movie_app/media_list.html
{% extends 'movie_app/base.html' %}
{% load static %}
{% block title %} {% if request.GET.is_series == '0' %} MOVIES {% elif request.GET.is_series == '1' %} SERIES {% else %} BROWSE BY GENRE {% endif %} {{ block.super }} {% endblock title %}
{% block content %}
<h1>{% if request.GET.is_series == '0' %} MOVIE LIST {% elif request.GET.is_series == '1' %} SERIES LIST {% else %}BROWSE BY GENRE {% endif %} </h1>
{% if request.GET.is_series == None %}
<div class="genre_filter">
    <ul> 
        {{ request.GET.is_series}}
        {% for filter_genre in genres %} 
        <li class="{% if filter_genre == genre %} current {% endif %}">  {{ filter_genre.link_filtered_medias}}<li>
        {% endfor %}
        </ul>
</div>
{% endif %}

<div class="search">
<form action="{% url 'all_media' %}" method="get">
    <input  type="text" name="search" value="{{ request.GET.search }}">
    <button type="submit">search</button>
</form>
</div>

    <ul class="media_list">
        {% for media in media_list %}
            <li class="media">
                 <a href="{% url 'media' media.pk %}">
                    {% if media.poster %}
                        <img src="{{media.poster.url}}">
                    {% else %}
                        <img src="{%  static 'movie_app/img/no_poster.jpg' %}">
                    {% endif %}
                     <h3 class="text-over-poster">{{ media }}</h3>
                    </a>
            </li>
        {% endfor %}
    </ul>

    <div class="paginator">
        {% if page_obj.has_previous%}
        <a href="?page=1">|&#11207;</a>
        <a href="?page={{ page_obj.previous_page_number }}">&#11207;</a>
    {% endif %}
    {{ page_obj.number }} 
    {% if page_obj.has_next %}
    <a href="?page={{ page_obj.next_page_number }}">&#11208;</a>
    <a href="?page={{ page_obj.paginator.num_pages }}">&#11208;|</a>
    {% endif %}
    </div>
{% endblock content %}

movie_database/movie_app/templates/movie_app/movies.html
{% extends 'movie_app/base.html' %}
{% load static %}
{% block title %} MOVIES {{ block.super }} {% endblock title %}
{% block content %}
<h1>MOVIE LIST</h1>
<p> movies go here <p>
    <ul class="media_list">
        {% for media in media_list %}
        {% comment %} <h3>{{ media.name }}</h3> {% endcomment %}
            <li class="media">
                 <a href="{% url 'media' media.pk %}">
                    {% if media.poster %}
                        <img src="{{media.poster.url}}">
                    {% else %}
                        <img src="{%  static 'movie_app/img/no_poster.jpg' %}">
                    {% endif %}
                     <h3>{{ media }}</h3>
                    </a>
            </li>
        {% endfor %}
    </ul>
{% endblock content %}

movie_database/movie_app/templates/movie_app/person.html
{% extends 'movie_app/base.html' %}
{% load static %}
{% block title %} {{person.name}} {{ block.super }} {% endblock title %}
{% block content %}

    <div class="media-details-container">
        <div class="media-details photo-size">
            {% if person.photo %}
              <img src="{{ person.photo.url }}">
            {% else %}
              <img src="{%  static 'movie_app/img/no_photo.jpg' %}">
            {% endif %}
        </div>
        <div class="media-details">
            <h1>{{ person }} </h1>
            <h3> {{ person.country }} </h3>
            <h2> Roles </h2>
            <ul>
                {% for role in person.cast_crew.all  %}
                <li> {{ role.role }} in <a class="cast" href="{% url 'media' role.media.pk %}"> {{ role.media }}</a> </li>
                {% endfor %}
            </ul>
        </div>
    <div>
{% endblock content %}

movie_database/movie_app/templates/movie_app/user_watchlist.html
{% extends 'movie_app/base.html' %}
{% load static %}
{% block title %} My Watchlist {{ block.super }} {% endblock title %}
{% block content %}
{% if watchlist_list %}
<div class="watchlist-container">
<h1> You have plans for {{converted_time}}</h1>
    <p> You have saved {{watchlist_count}} entries in the watchlist.</p>
        {% for watchlist_entry in watchlist_list %}
        <div class="watchlist-item">
            
            {% if watchlist_entry.media.poster %}
                <img src="{{ watchlist_entry.media.poster.url }}">
            {% else %}
                <img src="{%  static 'movie_app/img/no_poster.jpg' %}">
            {% endif %}
            
            <div class="watchlist-info">
            <a href="{% url 'media' watchlist_entry.media.pk %}">{{ watchlist_entry.media }} </a>
            <p>Duration: {{ watchlist_entry.media.convert_time }}</p>
            <p>Rating: {{ watchlist_entry.media.score }}</p>
            </div>
            <a class="button" href="{% url 'user_watchlist_delete' watchlist_entry.pk %}">X</a>
        </div> 
        {% endfor %}
        <div class="paginator">
            {% if page_obj.has_previous%}
            <a href="?page=1">|&#11207;</a>
            <a href="?page={{ page_obj.previous_page_number }}">&#11207;</a>
        {% endif %}
        {{ page_obj.number }} 
        {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}">&#11208;</a>
        <a href="?page={{ page_obj.paginator.num_pages }}">&#11208;|</a>
        {% endif %}
        </div>
    {% else %}
    <p>Looks like your watchlist is empty, you can choose some <a href="{% url 'all_media' %}?is_series=0">movies here</a> and <a href="{% url 'all_media' %}?is_series=1">series here</a>. <p>
    </div>
{% endif %}

    
   

{% endblock content %}

movie_database/movie_app/templates/movie_app/user_watchlist_add.html
{% extends 'movie_app/base.html' %}
{% block title %}Adding to watchlist {{ block.super }}{% endblock title %}
{% block content %}
<h1>Adding to watchlist</h1>
<div class="confirmation-message">
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <p>Are you sure you want to add this entry {{ object.media.name }} to your watchlist?</p>
    <div class="confirmation-message-buttons">
    <button type="submit" class="button">YES</button>
    <button class="button" href="{% url 'watchlist' %}">NO</button>
    </div>
</form>
</div>
{% endblock content %}

movie_database/movie_app/templates/movie_app/user_watchlist_delete.html
{% extends 'movie_app/base.html' %}
{% block title %}Deleting watchlist entry {{ block.super }}{% endblock title %}
{% block content %}
<h1>Deleting watchlist entry</h1>
<div class="confirmation-message">
<form method="post" action="">
    {% csrf_token %}
    <p>Are you sure you want to delete {{ object.media.name }} from your watchlist?</p>
        <div class="confirmation-message-buttons">
        <button type="submit" class="button">YES</button>
        <button class="button" href="{% url 'watchlist' %}">NO</button>
        </div>
</form>
</div>
{% endblock content %}